name: autodiff

{% set python_version = os.environ.get("PYTHON_VERSION", "3.10") %}

channels:
  - conda-forge
  - nvidia

dependencies:
  - catch2>=3
  - ccache  # [unix]
  - clangxx_osx-64  # [osx]
  - cmake
  - doxygen=1.9.1  # [linux]
  - eigen
  - git
  - graphviz  # [linux]
  - gxx_linux-64  # [linux]
  - lld  # [linux]
  - make  # [unix]
  - mkdocs
  - mkdocs-macros-plugin
  - mkdocs-material
  - ninja
  - pip
  - pre-commit
  - pybind11
  - pybind11-abi
  - pybind11-stubgen
  - python={{ python_version }}
  - shellcheck
  - vs2019_win-64  # [win]
  - cuda-toolkit  # [linux]
  - cuda-toolkit  # [windows]
