name: autodiff

dependencies:
  - black
  - cmake>=3.13
  - ninja
  - eigen
  - gxx_linux-64=7.3.0  # [linux]
  - ccache  # [unix]
  - pip
  - pip:
    - mkdocs
    - mkdocs-material
    - mkdocs-macros-plugin
  - pre-commit
  - shellcheck
